urls.py
from django.conf.urls.defaults import *
from django.contrib import admin


admin.autodiscover()

import os
PROJECT_DIR = os.path.dirname(__file__)

urlpatterns = patterns('',
    (r'^files/(?P<path>.*)$', 'django.views.static.serve', {'document_root': PROJECT_DIR + '/files'}),    
    (r'^$','fed.encuesta.views.index'),
    (r'^', include('fed.encuesta.urls')),
    
    (r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'login.html'}),
    (r'^logout/$', 'django.contrib.auth.views.logout', {'template_name': 'logout.html'}),
    (r'^admin/', include(admin.site.urls)),
)

encuesta/models.py
# -*- coding: UTF-8 -*-

from django.contrib.auth.models import User
from django.db import models
from django.template.defaultfilters import slugify
from fed.lugar.models import Departamento
from fed.lugar.models import Municipio
from fed.utils import *


CHOICE_MEDIO = (('estudios', 'Estudios'),
                ('foros', 'Foros'),
                ('cabildos', 'Cabildeos'),
                ('campania_tv', 'Campañas en televisión'),
                ('campania_radio', 'Campañas en radio'),
                ('talleres', 'Talleres de formación'),
                ('manifestaciones', 'Manifestaciones'),
                ('reuniones', 'Reuniones'),
                ('encuentros', 'Encuentros'))

CHOICE_REGION = (('comunitario', 'A nivel comunitario'),
                 ('municipal', 'A nivel municipal'),
                 ('departamental', 'A nivel departamental'),
                 ('regional', 'A nivel regional'),
                 ('nacional', 'A nivel nacional'),)
                 
CHOICE_DOCS = (('leyes', 'Leyes'),
               ('codigos', 'Códigos'),
               ('reglamentos', 'Reglamentos'),
               ('normativas', 'Normativas'),
               ('ordenanzas', 'Ordenanzas'),
               ('acuerdos', 'Acuerdos'), )

TIPO_CHOICE = ((0, 'Apoyo programático'),
               (1, 'Convocatoria pública'),
               (2, 'Pequeños proyectos'),
               (3, 'Actividades puntuales'),
               (4, 'Acciones de emergencia'),
               (5, 'Estrategias con grupos priorizados'))

CHOICE1 = (('si_hay', 'Si hay'), ('hay_pero', 'Hay un sistema pero no es eficiente'), ('no_hay', 'No hay'), )
CHOICE2 = (('si_hay', 'Si hay'), ('hay_pero', 'Hay un plan estratégico, pero no se utiliza'), ('no_hay', 'No hay'),)
CHOICE3 = (('ninguna', 'Ninguna'), ('proceso', 'En proceso'), ('logrado', 'Logrado'), )

class Organizacion(models.Model):
    nombre = models.TextField()
    nombre_corto = models.CharField(max_length=100)
    #tipo = models.IntegerField(choices=TIPO_CHOICE, verbose_name='Modalidad de apoyo')
    direccion = models.CharField(max_length=150)
    correo = models.EmailField(blank=True, default='example@example.com')
    contacto = models.CharField(max_length=200, blank=True, default='Ninguno')
    telefono = models.CharField(max_length=200, blank=True, default='Ninguno')
    antecedentes = models.TextField()
    user = models.ForeignKey(User, verbose_name='Usuario')
    #campos agregados a organizacion
    sistema = models.CharField(max_length=100, choices=CHOICE1, verbose_name='Cuenta con un sistema admitivo contable', blank=True, default='no-responde')
    plan = models.CharField(max_length=100, choices=CHOICE2, verbose_name='Utilizan su plan estratégico para mejorar sus capacidades de gestión en desarrollo de proyectos, consecusión y ejecución de recursos, comunicación', blank=True, default='no-responde')
    organizaciones = models.CharField(max_length=100, choices=CHOICE3, verbose_name='Apoyan a alguna org. de la diversidad sexual a tener personería', blank=True, default='no-responde')

    def __unicode__(self):
        return self.nombre_corto

    class Meta:
        verbose_name_plural = 'Organizaciones'
        ordering = ['nombre_corto']    

class Proyecto(models.Model):
    organizacion = models.ForeignKey(Organizacion)
    nombre = models.TextField()
    codigo = models.CharField(max_length=150, null=True, blank=True)
    tipo = models.IntegerField(choices=TIPO_CHOICE, verbose_name='Modalidad de apoyo')
    cobertura = models.TextField(verbose_name='Area de cobertura')
    duracion = models.CharField(max_length=30)
    monto = models.CharField('Monto solicitado a FED', null=True, blank=True, max_length=100)
    monto2 = models.CharField('Monto de contrapartida', null=True, blank=True, max_length=100)
    user = models.ForeignKey(User, verbose_name='Usuario')

    def __unicode__(self):
        return '%s' % (self.nombre)

    class Meta:
        verbose_name_plural = 'Proyectos'
        ordering = ['organizacion']

CHOICE_PERIODO = ((0, 'Enero - Febrero'),
                  (1, 'Marzo - Abril'),
                  (2, 'Mayo - Junio'),
                  (3, 'Julio - Agosto'),
                  (4, 'Septiembre - Octubre'),
                  (5, 'Noviembre - Diciembre'))
                  
CHOICE_ANIO = (('2010', '2010'), ('2011', '2011'), ('2012', '2012'))

class Encuesta(models.Model):
    organizacion = models.ForeignKey(Organizacion)
    proyecto = models.ForeignKey(Proyecto)
    periodo = models.IntegerField(choices=CHOICE_PERIODO, verbose_name='Período de informe')
    anio = models.CharField(choices=CHOICE_ANIO, verbose_name='Año', max_length=100)
    informe = models.FileField(upload_to=get_file_path, blank=True, null=True, help_text='Formatos adecuados: .doc, .pdf')
    user = models.ForeignKey(User)
    
    fileDir = 'informes/'

    def __unicode__(self):
        return '%s | %s | %s | %s' % (self.organizacion.nombre, self.proyecto.nombre, CHOICE_PERIODO[int(self.periodo)][1], self.anio)

    def get_periodo(self):
        return CHOICE_PERIODO[self.periodo][1]

    class Meta:
        verbose_name = 'Informe Contraparte'
        verbose_name_plural = 'Informes Contraparte'
        ordering = ['organizacion']

class InformeObjetivo3(models.Model):
    periodo = models.IntegerField(choices=CHOICE_PERIODO, verbose_name='Período de informe')
    anio = models.CharField(choices=CHOICE_ANIO, verbose_name='Año', max_length=100)

    def __unicode__(self):
        return '%s | %s ' % (CHOICE_PERIODO[int(self.periodo)][1], self.anio)

    class Meta:
        verbose_name = 'Informe Equipo Técnico'
        verbose_name_plural = 'Informes Equipo Técnico'

class TipoAccion(models.Model):
    nombre = models.CharField(max_length=100, verbose_name='Nombre acción')

    def __unicode__(self):
        return self.nombre

    class Meta:
        verbose_name_plural = 'Tipo Acciones'

class Meta(models.Model):
    nombre = models.CharField(max_length=100)
    slug = models.SlugField(unique=True, null=True, editable=False)

    def __unicode__(self):
        return self.nombre

    class Meta:
        verbose_name_plural = 'Metas'

    def save(self, force_insert=False, force_update=False):
        self.slug = slugify(self.nombre)
        super(Meta, self).save(force_insert, force_update)

class DatoInformeOb3(models.Model):
    tipo_accion = models.ForeignKey(TipoAccion)
    meta = models.ForeignKey(Meta)
    fecha = models.DateField(help_text='Fecha de actividad')
    organizacion = models.ManyToManyField(Organizacion, verbose_name=u'Organizaciónes')
    hombres = models.IntegerField(default=0)
    mujeres = models.IntegerField(default=0)
    informe = models.ForeignKey(InformeObjetivo3)

    def __unicode__(self):
        return 'Dato %s' % self.id

    class Meta:
        verbose_name = 'Actividad'
        verbose_name_plural = 'Actividades'

class Resultado(models.Model):
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField()

    def __unicode__(self):
        return self.nombre

    class Meta:
        verbose_name_plural = 'Resultados'

class Indicador(models.Model):
    resultado = models.ForeignKey(Resultado)
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField()
    slug = models.SlugField(unique=True, null=True, editable=False)
    
    def __unicode__(self):
        return self.nombre

    class Meta:
        verbose_name_plural = 'Indicadores'
        ordering = ['id']

    def save(self, force_insert=False, force_update=False):
        self.slug = slugify(self.nombre)
        super(Indicador, self).save(force_insert, force_update)

class ResultadoTrabajado(models.Model):
    resultado = models.ForeignKey(Resultado)    
    municipio = models.ManyToManyField(Municipio, verbose_name='Municipios')
    encuesta = models.ForeignKey(Encuesta)

    def __unicode__(self):
        return self.resultado.nombre

    class Meta:
        verbose_name = 'Resultado trabajado'
        verbose_name_plural = 'Resultados trabajados'


#VERBOSE_CANTIDAD = 'Número de acciones efectuadas para fomentar la existencia y aplicación efectiva de políticas públicas para posicionar el tema de la equidad e igualdad'
VERBOSE_CANTIDAD = 'Prevención de violencia'
VERBOSE_PARTICIPAN = 'Participantes'

class AccionEfectuadaMedio(models.Model):
    accion = models.CharField(max_length=100, choices=CHOICE_MEDIO, blank=True, default='no-responde', verbose_name='Tipo')
    cantidad = models.IntegerField(VERBOSE_CANTIDAD, blank=True, default=0)
    viol_part = models.IntegerField(VERBOSE_PARTICIPAN, blank=True, default=0)
    ssr = models.IntegerField('Salud sexual y reproductiva', blank=True, default=0)
    ssr_part = models.IntegerField(VERBOSE_PARTICIPAN, blank=True, default=0)
    vih_sida = models.IntegerField('VIH-SIDA', blank=True, default=0)
    vih_sida_part = models.IntegerField(VERBOSE_PARTICIPAN, blank=True, default=0)
    masculinidad = models.IntegerField('Masculinidad', blank=True, default=0)
    masc_part = models.IntegerField(VERBOSE_PARTICIPAN, blank=True, default=0)
    div_sexual = models.IntegerField('Diversidad sexual', blank=True, default=0)
    div_sexual_part = models.IntegerField(VERBOSE_PARTICIPAN, blank=True, default=0)
    equidad = models.IntegerField('Equidad de género', blank=True, default=0)
    participantes = models.IntegerField(VERBOSE_PARTICIPAN, blank=True, default=0)
    encuesta = models.ForeignKey(Encuesta)

    def __unicode__(self):
        return self.accion

    class Meta:
        verbose_name = 'Acciones impulsadas: Tipo de accion'
        verbose_name_plural = 'Acciones impulsadas: Tipo de acciones'

class AccionEfectuadaRegion(models.Model):
    accion = models.CharField(max_length=100, choices=CHOICE_REGION, blank=True, default='no-responde', verbose_name='Ambiente')
    cantidad = models.IntegerField(VERBOSE_CANTIDAD, blank=True, default=0)

encuesta/forms.py
# -*- coding: UTF-8 -*-

from django import forms
from django.forms import ModelForm
import datetime

from fed.encuesta.models import *

class InfluenciaForm(forms.Form):
    tipo = forms.MultipleChoiceField(choices=TIPO_CHOICE, label='Modalidad de apoyo')
    organizacion = forms.ModelMultipleChoiceField(queryset=Organizacion.objects.all(), label='Organizaciones')#, widget=forms.CheckboxSelectMultiple)
    resultado = forms.ModelMultipleChoiceField(queryset=Resultado.objects.all(), label='Resultados')
    periodo = forms.MultipleChoiceField(choices=CHOICE_PERIODO, label='Período')
    anio = forms.ChoiceField(choices=CHOICE_ANIO, label='Año')

class IndicadoresForm(forms.Form):
    tipo = forms.MultipleChoiceField(choices=TIPO_CHOICE, label='Modalidad de apoyo')
    organizacion = forms.ModelMultipleChoiceField(queryset=Organizacion.objects.all(), label='Organizaciones')#, widget=forms.CheckboxSelectMultiple)
    #municipio = forms.ModelMultipleChoiceField(queryset=Municipio.objects.all(), label='Municipios')
    periodo = forms.MultipleChoiceField(choices=CHOICE_PERIODO, label='Período')
    anio = forms.ChoiceField(choices=CHOICE_ANIO, label='Año')

templates/fed/indicador114.html
{% extends "base.html" %}
{% block extratitle %}Observatorios para vigilancia{% endblock %}
{% block contenido %}

{% include "bar3.html" %}
<div class="result_tables">
    <div class="titulo_indicadores">
        {{resultado.nombre}}: Observatorios para vigilancia
    </div>
    <div class="table_container">
        <table class="mostrar">
            <caption>Observatorios funcionando</caption>
            <thead>
                <tr>
                    <th>Acciones</th>
                    <th># de Observatorios</th>
                    <th>Acciones realizadas</th>
                    <th>Acciones divulgadas</th>
                    <th> % </th>
                </tr>
            </thead>
            {%for key, value in tabla.items%}
            <tr>
                <td>{{key}}</td>
                <td>{% if value.observatorio %}{{value.observatorio|floatformat}}{% else %}0{% endif %}</td>
                <td>{% if value.acciones_realizadas %}{{value.acciones_realizadas|floatformat}}{% else %}0{% endif %}</td>
                <td>{% if value.acciones_web %}{{value.acciones_web|floatformat}}{% else %}0{% endif %}</td>
                <td>{{value.prom|floatformat}}</td>
            </tr>
            {%endfor%}
        </table>
    </div>
</div>
<div class="clean"></div>
{% endblock %}

templates/fed/indicador121.html
{% extends "base.html" %}
{% block extratitle %}Discriminación de la diversidad sexual{% endblock %}
{% block contenido %}

{% include "bar3.html" %}
<div class="result_tables">
    <div class="titulo_indicadores">
        {{resultado.nombre}}: Acciones P&uacute;blicas
    </div>
    <div class="table_container">
        <table class="mostrar">
            <caption>Denuncias p&uacute;blicas y ante instancias del Estado de denuncia en contra de la discriminaci&oacute;n</caption>
            <thead>
                <tr>
                    <th>&nbsp;</th>                    
                    <th>En contra de la discriminaci&oacute;n a diversidad sexual</th>
                    <th>En contra de la discriminaci&oacute;n a discapacitados</th>
                    <th>En contra de la discriminaci&oacute;n a personas con VIH</th>
                    <th>En contra de la discriminaci&oacute;n por Etnia</th>
                    <th>En contra de la discriminaci&oacute;n a J&oacute;venes</th>
                </tr>
            </thead>
            {%for key, value in tabla.items%}
            <tr>
                <td>{{key}}</td>                
                <td>{% if value.sexual %}{{value.sexual|floatformat}}{% else %}0{% endif %}</td>
                <td>{% if value.discapacidad %}{{value.discapacidad|floatformat}}{% else %}0{% endif %}</td>
                <td>{% if value.vih %}{{value.vih|floatformat}}{% else %}0{% endif %}</td>
                <td>{% if vlaue.racial %}{{value.racial|floatformat}}{% else %}0{% endif %}</td>
                <td>{% if value.joven %}{{value.joven|floatformat}}{% else %}0{% endif %}</td>
            </tr>
            {%endfor%}  
        </table>
    </div>
</div>
<div class="clean"></div>
{% endblock %}

templates/fed/indicador222.html
{% extends "base.html" %}
{% block extratitle %}Grupos div. sexual y discapacidad{% endblock %}
{% block contenido %}

{% include "bar3.html" %}
<div class="result_tables">
    <div class="titulo_indicadores">
        {{resultado.nombre}}: Grupos div. sexual y discapacidad
    </div>
    <div class="table_container">
        <table class="mostrar">
            <caption>Acciones impulsadas por las para la prevenci&oacute;n de violencia BG con los grupos prioritarios</caption>
            <thead>
                <tr>
                    <th>&nbsp;</th>
                    <th>Acciones emprendidas por los grupos de la diversidad sexual</th>
                    <th>Acciones emprendidas por los grupos de personas con discapacidad</th>
                </tr>
            </thead>
            {%for key, value in tabla.items %}
            <tr>
                <td>{{key}}</td>
                <td>
                    {% if value.acciones_emprendidas %}
                    {{value.acciones_emprendidas|floatformat}}
                    {% else %}
                    0{% endif %}
                </td>                
                <td>
                    {% if value.acciones_impulsadas_masculinidad %}
                    {{value.acciones_impulsadas_masculinidad|floatformat}}
                    {% else %}
                    0{% endif %}
                </td>                
            </tr>
            {%endfor%}
        </table>
    </div>
</div>
<div class="clean"></div>
{% endblock %}

templates/fed/indicadores.html
{% extends "base.html" %}
{% block extratitle %}Avance de indicadores{% endblock %}
{% block extrahead %}
<link type="text/css" rel="stylesheet"  href="/files/css/django-admin-widgets.css">
<script type="text/javascript" src="/files/js/django-admin.multiselect.js"></script>
<script type="text/javascript" src="/files/js/jsi18n.js"></script>
<link type="text/css" rel="stylesheet"  href="/files/css/aux.css">
<script type="text/javascript">
    $(document).ready(function(){
        verificar();
        $("#id_tipo").change(function() {
            verificar();            
        });        
        
        $('#select_organizacion').click(function(){
            $('#id_organizacion option').each(function(){
                $(this).attr('selected', 'selected');
            });
            return false;
        });
        $('.tiene a').click(function(){
            var este = this;
            $('.results').animate({width: 'toggle'},
            function(){
                var id = $(este).attr('id');
                $('.'+id).slideDown()
            });
            return false;
        });
        $('.volver').click(function(){
            var este = this;
            $(este).parent().slideUp('fast', function() {
                $('.results').animate({width: 'toggle'});
            });
        });
        jQuery.each($("#id_municipio"), function () {
            // "Locations" can be any label you want
            SelectFilter.init(this.id, "", 0, "/media/");
        });
    });
    function verificar(){
        var lista = $('#id_tipo').val();
        if(lista==null){
            //$('#id_organizacion').attr('disabled', 'disabled');//each(function(){
            $('#id_organizacion').html('');
            //$(this).attr('disabled', 'disabled');
            //alert('tumadre');
            //});
        }else{
            var str = '';
            var lista = $('#id_tipo').val();
            if(lista!=null){
                for(var i=0;i<lista.length;i++){
                    if(i==lista.length-1){
                        str += lista[i];
                    }else{
                        str += lista[i]+',';
                    }
                }
                $.getJSON('/ajax/orgs/?ids='+str, function(data){
                    $('#id_organizacion').html('');
                    if(data){
                        $.each(data, function(i, item){
                            $('#id_organizacion').append($('<option></option>').val(item.id).html(item.nombre_corto));
                        });
                    }
                    {% for o in orgs_aux %}
                    $('#id_organizacion option[value={{o.id}}]').attr('selected', true);
                    {% endfor %}
                });
            }else{
                verificar();
            }
        }
    }
</script>
<style type="text/css">
    #id_organizacion{
        height: 140px;
    }
</style>
{% endblock %}
{% block contenido %}
<div class="bar estilo2">
    <div class="title">
        Formulario
    </div>
    <form action="." method="POST">{% csrf_token %}
        <label class="aux">{{form.tipo.label}}</label><br>
        {{form.tipo}}
        <br>
        <br>
        <label class="aux">{{form.organizacion.label}}</label><br>
        {{form.organizacion}}<br>
        <a href="#" class="selector-chooseall" id="select_organizacion">Selecciona todos</a>
        <!--<br>
        <div class="clean">
            <label class="aux">{{form.municipio.label}}</label><br>
            {{form.municipio}}
        </div>-->
        <br><br>
        <div class="clean">
            <label class="aux">{{form.periodo.label}}</label><br>
            {{form.periodo}}<br><br>
            <label class="aux">{{form.anio.label}}</label><br>
            {{form.anio}}<br><br>
        </div>
        <button type="submit">Consultar</button>
        <br>
        <br>
    </form>    
</div>
{% if bandera == 1 %}
<div class="resultados">    
    <div class="results">
        Resultados<br><br>
        {% for r in resultados %}
        {% if r.pk in datos %}
        <div class="tiene"><a id="ind{{r.pk}}" href="{{r.pk}}/">{{r.nombre}}</a></div>
        {% else %}
        <div class="notiene">{{r.nombre}}</div>
        {% endif %}
        {% endfor %}
        <div class="tiene"><a id="ind6" href="6/">Capacidad técnica de las OSC</a></div>
    </div>
    {% for r in resultados %}
    {% if r.pk in datos %}
    <div class="ind{{r.pk}} indicators">
        <button class="volver">Volver a Resultados</button><br><br>Resultado: {{r.nombre}}<br><br>
        Indicadores<br><br>
        {% for ind in r.indicador_set.all %}
        <div class="indicador"><a href="{{ind.slug}}/">{{ind.nombre}}</a></div>
        {% endfor %}
    </div>
    {% endif %}
    {% endfor %}
    <div class="ind6 indicators">
        <button class="volver">Volver a Resultados</button><br><br>Resultado: Capacidad técnica de las OSC<br><br>
        Indicadores<br><br>
        {% for meta in metas %}
        <div class="indicador"><a href="meta/{{meta.slug}}/">{{meta.nombre}}</a></div>
        {% endfor %}                
    </div>
</div>
{% endif %}
<div class="clean"></div>
{% endblock %}

templates/fed/influencia.html
{% extends "base.html" %}
{% block extratitle %}Area de influencia{% endblock %}
{% block extrahead %}
<link type="text/css" rel="stylesheet"  href="/files/css/django-admin-widgets.css">
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
<script type="text/javascript">
    var map;
    var markers = new Array();
    $(document).ready(function(){
        /*$('#id_organizacion').each(function(){
            $(this).remove();
        });*/
        verificar();
        $("#id_tipo").change(function() {
            verificar();
            var str = '';
            var lista = $('#id_tipo').val();
            if(lista!=null){
                for(var i=0;i<lista.length;i++){
                    if(i==lista.length-1){
                        str += lista[i];
                    }else{
                        str += lista[i]+',';
                    }
                }
                $.getJSON('/ajax/orgs/?ids='+str, function(data){
                    $('#id_organizacion').html('');
                    if(data){                                                
                        $.each(data, function(i, item){
                            $('#id_organizacion').append($('<option></option>').val(item.id).html(item.nombre_corto));
                        });
                    }
                });
            }else{
                verificar();
            }
        });

        $('#select_organizacion').click(function(){
            $('#id_organizacion option').each(function(){
                $(this).attr('selected', 'selected');
            });
            return false;
        });
        $('#select_resultados').click(function(){
            $('#id_resultado option').each(function(){
                $(this).attr('selected', 'selected');
            });
            return false;
        });
        
        var altura = $('.bar').height();                
        /*$('.mapa').height(altura);*/
        $('#map_canvas').height(altura-43);
        var infowindow = new google.maps.InfoWindow();

        var myLatlng = new google.maps.LatLng(13,-85);
        var myOptions = {
            zoom: 7,
            mapTypeControl: false,
            center: myLatlng,
            mapTypeId: google.maps.MapTypeId.ROADMAP
        }
        map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);

        $('#influencia_form').submit(function(){
            //var csrf = $('[name=csrfmiddlewaretoken]').val();
            markers.length = 0;
            if(checkear()){
                var datos = $('#influencia_form').serialize();
                $.post('/influencia/', datos,
                function(data){
                    map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);
                    $.each(data, function(i, item){
                        markers.push(new Array(item.punto[0], item.punto[1]));
                        var marker = new google.maps.Marker({
                            position: new google.maps.LatLng(item.punto[0], item.punto[1]),
                            map: map,
                            title:item.municipio
                        });
                        google.maps.event.addListener(marker, 'click', function() {
                            infowindow.open(map, marker);
                            var text = '<div class="infowindow">'+item.municipio+'<br><ul>';
                            $.each(item.proyectos, function(i, item){
                                text += '<li><a style="color:#7F7F7F;"href="/proyecto/' + item.id +'/">' + '['+item.organizacion__nombre_corto + '] ' + item.nombre + '</a></li>';
                            });
                            text += '</ul></div>';
                            infowindow.setContent(text);
                        });
                    });
                }, "json");
                return false;
            }else{
                return false;
            }
        });
        $('#guardar').click(function(){
            var url = '';            
            var centro = map.getCenter();            
            url = 'http://maps.google.com/maps/api/staticmap?center='+centro.lat().toFixed(2)+','+centro.lng().toFixed(2)+'&size=600x500&maptype=roadmap';
            if (markers.length>90){
                alert('La cantidad de puntos a superado el limite.\nActual: '+markers.length+'\nMax: 90');
                for (i=0; i < 90; i++){
                    url += '&markers='+markers[i][0].toFixed(2)+','+markers[i][1].toFixed(2)+'';
                }
            }else{
                for (i=0; i < markers.length; i++){
                    url += '&markers='+markers[i][0].toFixed(2)+','+markers[i][1].toFixed(2)+'';
                }
            }            
            url += '&sensor=false&zoom='+map.getZoom();            
            window.open(url, '_blank');
        });
        
    });
    function checkear(){
        var org, resul, per;
        if($('#id_organizacion').val() == null){
            alert('Seleccione una organización');
            org = false;
        }else{
            org = true;
        }
        if($('#id_resultado').val() == null){
            alert('Seleccione un resultado');
            resul = false;
        }else{
            resul = true;
        }
        if($('#id_periodo').val() == null){
            alert('Seleccione un periodo');
            per = false;
        }else{
            per = true;
        }
        
        if(org && resul && per){
            return true;
        }else{
            return false;
        }

    }

    function verificar(){
        var lista = $('#id_tipo').val();
        if(lista==null){
            //$('#id_organizacion').attr('disabled', 'disabled');//each(function(){
            $('#id_organizacion').html('');
            //$(this).attr('disabled', 'disabled');
            //alert('tumadre');
            //});
        }
    }
</script>
{% endblock %}
{% block contenido %}
<div class="bar">
    <div class="title">
        Formulario
    </div>
    <form action="." method="POST" id="influencia_form">{% csrf_token %}
        <label class="aux">{{form.tipo.label}}</label><br>
        {{form.tipo}}
        <br>
        <br>
        <label class="aux">{{form.organizacion.label}}</label><br>
        {{form.organizacion}}
        <a href="#" class="selector-chooseall" id="select_organizacion">Selecciona todos</a>
        <br>
        <label class="aux">{{form.resultado.label}}</label><br>
        {{form.resultado}}
        <a href="#" class="selector-chooseall" id="select_resultados">Selecciona todos</a>
        <br>
        <label class="aux">{{form.periodo.label}}</label><br>
        {{form.periodo}}<br><br>
        <label class="aux">{{form.anio.label}}</label><br>
        {{form.anio}}<br><br>
        <div class="clean">
            <button type="submit">Consultar</button><button name="png" id="guardar" type="button">Guardar Mapa</button>
        </div>
        <br>
    </form>
</div>
<div class="mapa">
    <div class="title_map"><a href="/lista/">Ver lista</a></div>
    <div id="map_canvas">

    </div>
</div>
<div class="clean"></div>

{% endblock %}