urls.py
from django.conf.urls.defaults import *
from django.contrib import admin


admin.autodiscover()

import os
PROJECT_DIR = os.path.dirname(__file__)

urlpatterns = patterns('',
    (r'^files/(?P<path>.*)$', 'django.views.static.serve', {'document_root': PROJECT_DIR + '/files'}),    
    (r'^$','fed.encuesta.views.index'),
    (r'^', include('fed.encuesta.urls')),
    
    (r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'login.html'}),
    (r'^logout/$', 'django.contrib.auth.views.logout', {'template_name': 'logout.html'}),
    (r'^admin/', include(admin.site.urls)),
)

encuesta/models.py
# -*- coding: UTF-8 -*-

from django.contrib.auth.models import User
from django.db import models
from django.template.defaultfilters import slugify
from fed.lugar.models import Departamento
from fed.lugar.models import Municipio
from fed.utils import *


CHOICE_MEDIO = (('estudios', 'Estudios'),
                ('foros', 'Foros'),
                ('cabildos', 'Cabildeos'),
                ('campania_tv', 'Campañas en televisión'),
                ('campania_radio', 'Campañas en radio'),
                ('talleres', 'Talleres de formación'),
                ('manifestaciones', 'Manifestaciones'),
                ('reuniones', 'Reuniones'),
                ('encuentros', 'Encuentros'))

CHOICE_REGION = (('comunitario', 'A nivel comunitario'),
                 ('municipal', 'A nivel municipal'),
                 ('departamental', 'A nivel departamental'),
                 ('regional', 'A nivel regional'),
                 ('nacional', 'A nivel nacional'),)
                 
CHOICE_DOCS = (('leyes', 'Leyes'),
               ('codigos', 'Códigos'),
               ('reglamentos', 'Reglamentos'),
               ('normativas', 'Normativas'),
               ('ordenanzas', 'Ordenanzas'),
               ('acuerdos', 'Acuerdos'), )

TIPO_CHOICE = ((0, 'Apoyo programático'),
               (1, 'Convocatoria pública'),
               (2, 'Pequeños proyectos'),
               (3, 'Actividades puntuales'),
               (4, 'Acciones de emergencia'),
               (5, 'Estrategias con grupos priorizados'))

CHOICE1 = (('si_hay', 'Si hay'), ('hay_pero', 'Hay un sistema pero no es eficiente'), ('no_hay', 'No hay'), )
CHOICE2 = (('si_hay', 'Si hay'), ('hay_pero', 'Hay un plan estratégico, pero no se utiliza'), ('no_hay', 'No hay'),)
CHOICE3 = (('ninguna', 'Ninguna'), ('proceso', 'En proceso'), ('logrado', 'Logrado'), )

class Organizacion(models.Model):
    nombre = models.TextField()
    nombre_corto = models.CharField(max_length=100)
    #tipo = models.IntegerField(choices=TIPO_CHOICE, verbose_name='Modalidad de apoyo')
    direccion = models.CharField(max_length=150)
    correo = models.EmailField(blank=True, default='example@example.com')
    contacto = models.CharField(max_length=200, blank=True, default='Ninguno')
    telefono = models.CharField(max_length=200, blank=True, default='Ninguno')
    antecedentes = models.TextField()
    user = models.ForeignKey(User, verbose_name='Usuario')
    #campos agregados a organizacion
    sistema = models.CharField(max_length=100, choices=CHOICE1, verbose_name='Cuenta con un sistema admitivo contable', blank=True, default='no-responde')
    plan = models.CharField(max_length=100, choices=CHOICE2, verbose_name='Utilizan su plan estratégico para mejorar sus capacidades de gestión en desarrollo de proyectos, consecusión y ejecución de recursos, comunicación', blank=True, default='no-responde')
    organizaciones = models.CharField(max_length=100, choices=CHOICE3, verbose_name='Apoyan a alguna org. de la diversidad sexual a tener personería', blank=True, default='no-responde')

    def __unicode__(self):
        return self.nombre_corto

    class Meta:
        verbose_name_plural = 'Organizaciones'
        ordering = ['nombre_corto']    

class Proyecto(models.Model):
    organizacion = models.ForeignKey(Organizacion)
    nombre = models.TextField()
    codigo = models.CharField(max_length=150, null=True, blank=True)
    tipo = models.IntegerField(choices=TIPO_CHOICE, verbose_name='Modalidad de apoyo')
    cobertura = models.TextField(verbose_name='Area de cobertura')
    duracion = models.CharField(max_length=30)
    monto = models.CharField('Monto solicitado a FED', null=True, blank=True, max_length=100)
    monto2 = models.CharField('Monto de contrapartida', null=True, blank=True, max_length=100)
    user = models.ForeignKey(User, verbose_name='Usuario')

    def __unicode__(self):
        return '%s' % (self.nombre)

    class Meta:
        verbose_name_plural = 'Proyectos'
        ordering = ['organizacion']

CHOICE_PERIODO = ((0, 'Enero - Febrero'),
                  (1, 'Marzo - Abril'),
                  (2, 'Mayo - Junio'),
                  (3, 'Julio - Agosto'),
                  (4, 'Septiembre - Octubre'),
                  (5, 'Noviembre - Diciembre'))
                  
CHOICE_ANIO = (('2010', '2010'), ('2011', '2011'), ('2012', '2012'))

class Encuesta(models.Model):
    organizacion = models.ForeignKey(Organizacion)
    proyecto = models.ForeignKey(Proyecto)
    periodo = models.IntegerField(choices=CHOICE_PERIODO, verbose_name='Período de informe')
    anio = models.CharField(choices=CHOICE_ANIO, verbose_name='Año', max_length=100)
    informe = models.FileField(upload_to=get_file_path, blank=True, null=True, help_text='Formatos adecuados: .doc, .pdf')
    user = models.ForeignKey(User)
    
    fileDir = 'informes/'

    def __unicode__(self):
        return '%s | %s | %s | %s' % (self.organizacion.nombre, self.proyecto.nombre, CHOICE_PERIODO[int(self.periodo)][1], self.anio)

    def get_periodo(self):
        return CHOICE_PERIODO[self.periodo][1]

    class Meta:
        verbose_name = 'Informe Contraparte'
        verbose_name_plural = 'Informes Contraparte'
        ordering = ['organizacion']

class InformeObjetivo3(models.Model):
    periodo = models.IntegerField(choices=CHOICE_PERIODO, verbose_name='Período de informe')
    anio = models.CharField(choices=CHOICE_ANIO, verbose_name='Año', max_length=100)

    def __unicode__(self):
        return '%s | %s ' % (CHOICE_PERIODO[int(self.periodo)][1], self.anio)

    class Meta:
        verbose_name = 'Informe Equipo Técnico'
        verbose_name_plural = 'Informes Equipo Técnico'

class TipoAccion(models.Model):
    nombre = models.CharField(max_length=100, verbose_name='Nombre acción')

    def __unicode__(self):
        return self.nombre

    class Meta:
        verbose_name_plural = 'Tipo Acciones'

class Meta(models.Model):
    nombre = models.CharField(max_length=100)
    slug = models.SlugField(unique=True, null=True, editable=False)

    def __unicode__(self):
        return self.nombre

    class Meta:
        verbose_name_plural = 'Metas'

    def save(self, force_insert=False, force_update=False):
        self.slug = slugify(self.nombre)
        super(Meta, self).save(force_insert, force_update)

class DatoInformeOb3(models.Model):
    tipo_accion = models.ForeignKey(TipoAccion)
    meta = models.ForeignKey(Meta)
    fecha = models.DateField(help_text='Fecha de actividad')
    organizacion = models.ManyToManyField(Organizacion, verbose_name=u'Organizaciónes')
    hombres = models.IntegerField(default=0)
    mujeres = models.IntegerField(default=0)
    informe = models.ForeignKey(InformeObjetivo3)

    def __unicode__(self):
        return 'Dato %s' % self.id

    class Meta:
        verbose_name = 'Actividad'
        verbose_name_plural = 'Actividades'

class Resultado(models.Model):
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField()

    def __unicode__(self):
        return self.nombre

    class Meta:
        verbose_name_plural = 'Resultados'

class Indicador(models.Model):
    resultado = models.ForeignKey(Resultado)
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField()
    slug = models.SlugField(unique=True, null=True, editable=False)
    
    def __unicode__(self):
        return self.nombre

    class Meta:
        verbose_name_plural = 'Indicadores'
        ordering = ['id']

    def save(self, force_insert=False, force_update=False):
        self.slug = slugify(self.nombre)
        super(Indicador, self).save(force_insert, force_update)

class ResultadoTrabajado(models.Model):
    resultado = models.ForeignKey(Resultado)    
    municipio = models.ManyToManyField(Municipio, verbose_name='Municipios')
    encuesta = models.ForeignKey(Encuesta)

    def __unicode__(self):
        return self.resultado.nombre

    class Meta:
        verbose_name = 'Resultado trabajado'
        verbose_name_plural = 'Resultados trabajados'


#VERBOSE_CANTIDAD = 'Número de acciones efectuadas para fomentar la existencia y aplicación efectiva de políticas públicas para posicionar el tema de la equidad e igualdad'
VERBOSE_CANTIDAD = 'Prevención de violencia'
VERBOSE_PARTICIPAN = 'Participantes'

class AccionEfectuadaMedio(models.Model):
    accion = models.CharField(max_length=100, choices=CHOICE_MEDIO, blank=True, default='no-responde', verbose_name='Tipo')
    cantidad = models.IntegerField(VERBOSE_CANTIDAD, blank=True, default=0)
    viol_part = models.IntegerField(VERBOSE_PARTICIPAN, blank=True, default=0)
    ssr = models.IntegerField('Salud sexual y reproductiva', blank=True, default=0)
    ssr_part = models.IntegerField(VERBOSE_PARTICIPAN, blank=True, default=0)
    vih_sida = models.IntegerField('VIH-SIDA', blank=True, default=0)
    vih_sida_part = models.IntegerField(VERBOSE_PARTICIPAN, blank=True, default=0)
    masculinidad = models.IntegerField('Masculinidad', blank=True, default=0)
    masc_part = models.IntegerField(VERBOSE_PARTICIPAN, blank=True, default=0)
    div_sexual = models.IntegerField('Diversidad sexual', blank=True, default=0)
    div_sexual_part = models.IntegerField(VERBOSE_PARTICIPAN, blank=True, default=0)
    equidad = models.IntegerField('Equidad de género', blank=True, default=0)
    participantes = models.IntegerField(VERBOSE_PARTICIPAN, blank=True, default=0)
    encuesta = models.ForeignKey(Encuesta)

    def __unicode__(self):
        return self.accion

    class Meta:
        verbose_name = 'Acciones impulsadas: Tipo de accion'
        verbose_name_plural = 'Acciones impulsadas: Tipo de acciones'

class AccionEfectuadaRegion(models.Model):
    accion = models.CharField(max_length=100, choices=CHOICE_REGION, blank=True, default='no-responde', verbose_name='Ambiente')
    cantidad = models.IntegerField(VERBOSE_CANTIDAD, blank=True, default=0)

templates/bar3.html
<script type="text/javascript">
    $(document).ready(function(){
       var alto = $('.result_tables').height();
       var alto_barra = $('.bar3').height();
       if (alto>alto_barra){
           $('.bar3').height(alto);
       }
    });
</script>
<div class="bar3">
    <div class="nav2">        
        <a href="/indicadores/">Nueva Consulta</a> <img src="/files/images/mas2.png" alt=""><br>
        <a href="/indicadores/?q=1">Volver a Resultados</a><img src="/files/images/atras.png" alt="">
    </div>    
    <div class="otros_indicadores">
        {% for i in resultado.indicador_set.all %}
        <a href="/indicadores/{{i.slug}}">{{i.nombre}}</a>
        {% endfor %}
    </div>
</div>

templates/bar4.html
<script type="text/javascript">
    $(document).ready(function(){
       var alto = $('.result_tables').height();
       var alto_barra = $('.bar3').height();
       if (alto>alto_barra){
           $('.bar3').height(alto);
       }
    });
</script>
<div class="bar3">
    <div class="nav2">        
        <a href="/indicadores/">Nueva Consulta</a> <img src="/files/images/mas2.png" alt=""><br>
        <a href="/indicadores/?q=1">Volver a Resultados</a><img src="/files/images/atras.png" alt="">
    </div>    
    <div class="otros_indicadores">
        {% for i in metas %}
        <a href="/indicadores/meta/{{i.slug}}">{{i.nombre}}</a>
        {% endfor %}
    </div>
</div>

templates/base.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
        <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
        <meta http-equiv="content-type" content="text/html; charset=UTF-8"/>
        <style type="text/css">
            #map_canvas { height: 500px; width: 709px; }
        </style>
        <title>Sistema de Informacion FED | {% block extratitle %}{% endblock %}</title>
        <link type="text/css" rel="stylesheet"  href="/files/css/fed.css" >
        <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>        
        {% if user.is_authenticated %}
        <script type="text/javascript">
            $(document).ready(function(){
                $('#influencia').hover(function(){
                    $('#influencia img').attr('src', '/files/images/influencia_hover.png');
                });
                $('#influencia').mouseout(function(){
                    $('#influencia img').attr('src', '/files/images/influencia.png');
                });
                $('#indicadores').hover(function(){
                    $('#indicadores img').attr('src', '/files/images/indicadores_hover.png');
                });
                $('#indicadores').mouseout(function(){
                    $('#indicadores img').attr('src', '/files/images/indicadores.png');
                });
            });
        </script>
        {% endif %}
        {% block extrahead %}{% endblock %}
    </head>
    <body>
        <div id="wrapper">
            <div class="banner">
                <div class="logo" id="logo">
                    <a href="/"><img src="/files/images/logo.png" alt="Fed Hivos"></a>

                    <img src="/files/images/vline.png" alt="" class="vline">
                </div>
                <div class="title">
                    Sistema de Informaci&oacute;n
                </div>
                <div class="nav">
                    {% if user.is_authenticated %}
                    <button type="button" onclick="window.location.href='/'">Inicio</button>
                    <button type="button" onclick="window.location.href='/#!'">Ayuda</button>
                    {% endif %}
                </div>
                <div class="clean"></div>
            </div>
            <div class="tools">
                {% if user.is_authenticated %}
                <div class="salidas">
                    <a href="/influencia/" id="influencia"><img src="/files/images/influencia.png" alt="Area de influencia"></a>
                    <a href="/indicadores/" id="indicadores"><img src="/files/images/indicadores.png" alt="Avance de indicadores"></a>
                </div>
                <div class="loginfo">
                    <img src="/files/images/avatar.png" alt="" class="avatar">
                    <div class="username">  {{user.username}}</div>
                    <img src="/files/images/vline2.png" alt="-" class="avatar">
                    <div class="username">
                        <a href="/admin/"><img src="/files/images/admin.png" alt="Admin">Administraci&oacute;n</a><br>
                        <a href="/logout/"><img src="/files/images/salir.png" alt="Cerrar Sesion">Salir</a>
                    </div>
                </div>
                {% else %}
                <div class="text">Entrar al sistema</div>
                {% endif %}
            </div>
            <div class="content">
                <!--<div class="top"></div>-->
                <div class="contenedor">
                    {% block contenido %}
                    {% endblock %}
                </div>
                <!--<div class="bottom"></div>-->
            </div>
            <div class="footer">
                Desarrollado por <a class="abajo" href="http://www.simas.org.ni">SIMAS</a> bajo plataforma
                <a class="abajo" href="http://www.djangoproject.com">Django</a>
            </div>
        </div>
    </body>
</html>

templates/index.html
{% extends "base.html" %}
{% block extratitle %}Home{% endblock %}
{% block contenido %}
<div class="ultimas">
    <span class="title">ULTIMAS ACCIONES</span>
    {% for i in informes %}
    <div class="registro">
        <div class="mas">
            <img src="/files/images/mas.png" alt="mas">
        </div>
        <div class="mastext">
            <span class="entry">Agregado informe {{i.get_periodo|lower}} año {{i.anio}}</span><br>
            <span class="data">Usuario: {{i.user}}, organización: {{i.organizacion}}</span>
        </div>
        <img class="hline" src="/files/images/hline.png" alt="-">
    </div>
    {% endfor %}
    <br>
</div>
<img class="vline3" src="/files/images/vline3.png" alt="-">
<div class="acerca">
    <span class="title">ACERCA DEL SISTEMA</span>
    <div class="desc">
        El Fondo para la Equidad de Género y los Derechos Sexuales y Reproducivos es un mecanismo  común  de  apoyo  de  la  cooperación  internacional  a  las  organizaciones  de la sociedad civil nicaragüense que promueven la equidad e igualdad de género y el pleno reconocimiento y ejercicio de los derechos sexuales y derechos reproductivos de la ciudadanía nicaragüense.
        <br><br>Ha contribuido no sólo a la disminución de los costos de la ayuda, sino que ha permitido, por su apertura hacia las organizaciones de la sociedad civil, potenciar capacidades y fortalezas existentes, así como estimular la creación y desarrollo de iniciativas novedosas. Los donantes del FED son los siguientes:Noruega, Suecia, Finlandia, Países Bajos, Austria, Luxemburgo, Dinamarca, GTZ/Alemania y UNFPA.
    </div>
</div>
<div class="clean"></div>
{% endblock %}

templates/login.html
{% extends "base.html" %}
{% block extratitle %}
Iniciar Sesi&oacute;n
{% endblock %}
{% block extrahead %}
<script type="text/javascript">
    $(document).ready(function(){
        $('#id_password').val('password');
        $('#id_username').val('usuario');
        $('#id_password').click(function(){
            if($(this).val()=='password'){$(this).val('')}
        });
        $('#id_password').focus(function(){
            if($(this).val()=='password'){$(this).val('')}
        });
        $('#id_password').blur(function(){
            if($(this).val()==''){$(this).val('password')}
        });
        $('#id_username').click(function(){
            if($(this).val()=='usuario'){$(this).val('')}
        });
        $('#id_username').focus(function(){
            if($(this).val()=='usuario'){$(this).val('')}
        });
        $('#id_username').blur(function(){
            if($(this).val()==''){$(this).val('usuario')}
        });
    });
</script>
{% endblock%}
{% block contenido %}
<div class="login">
    <div>
        <form action="{% url django.contrib.auth.views.login %}" method="POST">{% csrf_token %}
            <label>Usuario</label><br>
            <input type="text" name="username" id="id_username" /><br><br>
            <label>Contrase&ntilde;a</label><br>
            <input type="password" name="password" id="id_password" /><br><br>
            <button type="submit" class="entrar">Entrar</button>
            <input type="hidden" name="next" value="{{ next }}" />
        </form>
    </div>
</div>
{% endblock %}

templates/logout.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
  <head>
    <title></title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <script type="text/javascript">
        window.location = '/'
    </script>
  </head>
  <body>
    
  </body>
</html>

templates/organizacion.html
{% extends "base.html" %}
{% block extratitle %}{{organizacion.nombre_corto}}{% endblock %}
{% block contenido %}
<div class="acerca">
    <div class="title_project org">
        <div class="proyecto_nombre">Organizaci&oacute;n</div>
        {{organizacion.nombre}}
    </div>
    <div class="proyecto_info">
        <div class="direccion">
            <span class="blue bold">Direcci&oacute;n</span><br>
            {{organizacion.direccion}}
        </div>
        <div class="monto">
            <span class="blue bold">Correo</span><br>
            {{organizacion.correo}}
        </div>
        <img src="/files/images/pointed_line.png" alt="line" class="pointed_line">
        <div class="monto2">
            <span class="blue bold">Persona de contacto</span><br>
            {{organizacion.contacto}}
        </div>
        <div class="monto">
            <span class="blue bold">Tel&eacute;fono</span><br>
            {{organizacion.telefono}}
        </div>
        <img src="/files/images/pointed_line.png" alt="line" class="pointed_line">
        <div class="monto2">
            <span class="blue bold">Antecedentes de la organización</span><br>
            {{organizacion.antecedentes}}
        </div>        
        <div class="clean"></div>
        <br><br>
    </div>
</div>
<div class="ultimas">    
    <table class="mostrar">        
        <thead>
            <tr>
                <th>Proyectos</th>
            </tr>
        </thead>
        <tbody>
            {% for proyecto in organizacion.proyecto_set.all %}
            <tr><td><a href="/proyecto/{{proyecto.pk}}/">{{proyecto.nombre}}</a> | Informes:
                    {% for e in proyecto.encuesta_set.all %}
                    {% if e.informe %}
                    <a href="{{e.informe.url}}">{{e.get_periodo}} / {{e.anio}}</a>{% if forloop.last %}{% else %}, {% endif %}
                    {% endif %}
                    {% endfor %}                    
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
<div class="clean"></div>
{% endblock %}

templates/proyecto.html
{% extends "base.html" %}
{% block extratitle %}Home{% endblock %}
{% block contenido %}
<div class="ultimas">
    <div class="title_project">
        <div class="proyecto_nombre">Proyecto</div>
        {{proyecto.nombre}}
    </div>
    <div class="proyecto_info">
        <span class="naranja bold">Area de cobertura</span><br>        
        {{proyecto.cobertura}}
        <img src="/files/images/pointed_line.png" alt="line" class="pointed_line">
        <div class="duracion">
            <span class="naranja bold">Duraci&oacute;n</span><br>
            {{proyecto.duracion}}
        </div>
        <div class="monto">
            <span class="naranja bold">Monto solicitado de FED</span><br>
            {{proyecto.monto}}
        </div>
        <div class="monto">
            <span class="naranja bold">Monto de contrapartida</span><br>
            {{proyecto.monto2}}
        </div>
        <img src="/files/images/pointed_line.png" alt="line" class="pointed_line">
        <div class="clean"></div>
        <br><br>
    </div>
</div>
<div class="acerca">
    <div class="title_project org">
        <div class="proyecto_nombre">Organizaci&oacute;n</div>
        <a href="/organizacion/{{proyecto.organizacion.pk}}/">{{proyecto.organizacion.nombre}}</a>
    </div>
    <div class="proyecto_info">
        <div class="direccion">
            <span class="blue bold">Direcci&oacute;n</span><br>
            {{proyecto.organizacion.direccion}}
        </div>
        <div class="monto">
            <span class="blue bold">Correo</span><br>
            {{proyecto.organizacion.correo}}
        </div>
        <img src="/files/images/pointed_line.png" alt="line" class="pointed_line">
        <div class="monto2">
            <span class="blue bold">Persona de contacto</span><br>
            {{proyecto.organizacion.contacto}}
        </div>
        <div class="monto">
            <span class="blue bold">Tel&eacute;fono</span><br>
            {{proyecto.organizacion.telefono}}
        </div>
        <img src="/files/images/pointed_line.png" alt="line" class="pointed_line">
        <div class="monto2">
            <span class="blue bold">Antecedentes de la organización</span><br>
            {{proyecto.organizacion.antecedentes}}
        </div>        
        <div class="clean"></div>
        <br><br>
    </div>
</div>
<div class="clean"></div>
{% endblock %}